function editsource(input)
% SYNTAX:
%        editsource(inputstructure)
%
% This function is used to view the analysis code that generated a batched
% results structure (using the "batch" function).  The "inputstructure" is
% simply the output generated by "batch", which contains the entire
% analysis code used to generate the associated Results.
%
% Created by WA  6/8/2011

if ~isstruct(input),
    error('Input to "editsource" should be the data structure created by "batch"');
end

if ~isfield(input, 'AnalysisFunctionText'),
    error('Input to "editsource" must have the field "AnalysisFunctionText" created by "batch"');
end

fxn = input.AnalysisFunction;
txt = input.AnalysisFunctionText;

MLdir = getpref('MonkeyLogic', 'Directories');

[pname fname] = fileparts(fxn);
fxn = [MLdir.ExperimentDirectory fname '_source.m'];

fid = fopen(fxn, 'w');
if fid < 0,
    error('Cannot create %s', fxn)
end

numlines = length(txt);
for i = 1:numlines,
    if i == 2,
        fprintf(fid, '%%Analysis source for batched function "%s" as executed on %s\r', fname, input.AnalysisTime);
    end
    fprintf(fid, '%s\r', txt{i});
end

fclose(fid);

edit(fxn);